version: "3.3"

services:
  spark-master:
    image: bde2020/spark-master:2.4.3-hadoop2.7
    container_name: spark-master
    expose:
      - "7001"
      - "7002"
      - "7003"
      - "7004"
      - "7005"
      - "7006"
      - "7077"
      - "6066"
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "9090:8080"
    volumes:
      - /Users/alejandroferrin/UdemyProjects/spark-cluster-docker/conf:/spark/conf
      - /Users/alejandroferrin/UdemyProjects/spark-cluster-docker/output:/output
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:2.4.3-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8081"
    volumes:
    - /Users/alejandroferrin/UdemyProjects/spark-cluster-docker/conf:/spark/conf
    environment:
#      - "SPARK_WORKER_CORES=1"
#      - "SPARK_WORKER_MEMORY=1000M"
      - "SPARK_MASTER=spark://spark-master:7077"
